const defaultSettings = {
  defaults: {
    ConfigType: "Violin",
    networkProjection: "vertical",
    hoverAnnotation: "none",
    highlightAnnotation: false,
    showPoints: true,
    nodeColorConfig: "field",
    nodeColor: "#CCCCCC", 
    nodeRender: "normal", 
    nodeFillOpacity: .35,
    nodeStrokeOpacity: .5,
    nodeSize: 'none', 
    markerMinRadius: 1, 
    markerMaxRadius: 25,
    sumRender: "normal", 
    sumFillOpacity: .35,
    sumStrokeOpacity: .5,
  },
  defaultKeys: [ 
    'ConfigType',
    'networkProjection',
    'hoverAnnotation',
    'highlightAnnotation',
    'showPoints',
    'nodeColorConfig',
    'nodeColor',
    'nodeRender',
    'nodeFillOpacity',
    'nodeStrokeOpacity',
    'nodeSize',
    'markerMinRadius',
    'markerMaxRadius',
    'sumRender',
    'sumFillOpacity',
    'sumStrokeOpacity',
  ]
}

export default defaultSettings;